### ISSUE TITLE
spl_autoload_register preload bug in static distrib file, integrate composer in distributables?

### ISSUE THREAD

**Issue by wbob** [girosolution/girocheckout_sdk#1]
hello! So there's a composer package, nice! - it will take care of optimized autoloading - only loading classes with the ` girosolution\GiroCheckout_SDK\` prefix. Though as of writing the standalone GiroCheckout PHP SDK on [api.girocheckout.de](http://api.girocheckout.de/phpsdk:start) and within the Plugin zipfiles do not include the composer integration and have a `lib/GiroCheckout_SDK/GiroCheckout_SDK.php` not present in this repo instead.

Unfortunately the implementation will check for presence of project wide classes in its path because of its `preload=true` parameter to `spl_autoload_register`. In some PHP configurations (open_basedir set, disabled realpath_cache) this will have a grave performance impact.

I think it would be nice to have the distributables zipfiles with composer too or change the autoloading to something along the lines of the PSR-4 [example](https://www.php-fig.org/psr/psr-4/examples/#closure-example):
`GiroCheckout_SDK.php`
```
        public static function load($classname) {
+               if (strpos($classname, 'GiroCheckout_SDK') === FALSE) {
+                       // move to next autoloader if prefix does not belong to plugin
+                       return;
+               }
```
I guess you planned for this anyway in the future, but I want to point out it's very much worth the effort.

**Comment by michaelheumann** [comment]
Hi, I'm so sorry I didn't see your post earlier.

As of using composer in the plugins and the standalone SDK, the latter will be maintained as is to support existing implementations that use it and also to provide an alternative way for someone who doesn't want to use composer.  The plugins may be switched to the composer version in the future, if the underlying shop systems support it.

Regarding your suggestions with spl_autoload_register, I understand it also refers to the non-composer SDK.  We appreciate the input and will add this very useful improvement in the next release.

Thanks!

**Comment by wbob** [comment]
you're welcome, it was definitely an interesting issue. With set open_basedir the missing exclusion of other classpaths with preload enabled makes for many unnecessary filesystem lookups (project classes * directory nesting level) - slowing down execution.
This magnified a php behaviour previous unknown to me and found its way into related documentation - php/php-src@5ac9990 / symfony/symfony-docs#10800 / [php.net/manual/en/ini.core.php](https://www.php.net/manual/en/ini.core.php#ini.sect.performance). I really campaigned for that one :)
