### ISSUE TITLE
PaymentPage with timeout

### ISSUE THREAD

**Issue by eschricker** [girosolution/girocheckout_sdk#3]
Hello, 
I am using a payment page with timeout in my test account. The timer is shown on the payment page, but when it times out, I don't get a notification via the notifyUrl. I would prefere a notification like "the payment failed". 

Is this due to the test account or are such notifications not possible.

When I create a payment page request the response contains an URL like `https://pay.girocheckout.de/<ID>` which will be redirected to `https://pay.girocheckout.de/v1/paypage/de/<ID>`

When the page without `v1/paypage/de` will be opened again, the timer starts from scratch. 

Is it possible to get  a URL with the `v1/paypage/de` directly, so that reloading will not reset the timer?

**Comment by michaelheumann** [comment]
Hi, sorry for the late reply, but I think we already discussed and resolved this on a parallel channel (GiroSolution support.)

Just for completeness:

- Notifications can only be sent once a payment transaction has been initialized by selecting and submitting a payment method.
- The timeout issue has been addressed lately with the extension of the expiryDate parameter, which now also supports passing a time.  This way, the whole payment link can be disabled from a certain moment on.
